-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 14:50:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mechanicalworkshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mechanicalworkshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mechanicalworkshop` DEFAULT CHARACTER SET utf8 ;
USE `mechanicalworkshop` ;

-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`person` (
  `id_person` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(155) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profile` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `rg` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_person`),
  UNIQUE INDEX `idperson_UNIQUE` (`id_person` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`admin` (
  `person_id_person` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_admin_person_idx` (`person_id_person` ASC),
  CONSTRAINT `fk_admin_person`
    FOREIGN KEY (`person_id_person`)
    REFERENCES `mechanicalworkshop`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`client` (
  `id_client` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(155) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(10) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `idclient_UNIQUE` (`id_client` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`mechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`mechanic` (
  `person_id_person` INT(10) UNSIGNED NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `specialty` TEXT NOT NULL,
  INDEX `fk_mechanic_person1_idx` (`person_id_person` ASC),
  CONSTRAINT `fk_mechanic_person1`
    FOREIGN KEY (`person_id_person`)
    REFERENCES `mechanicalworkshop`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`mechanic_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`mechanic_team` (
  `id_mechanic_team` INT UNSIGNED NOT NULL,
  `name` VARCHAR(155) NOT NULL,
  `function` TEXT NOT NULL,
  `mechanic_person_id_person` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_mechanic_team`),
  UNIQUE INDEX `idmechanic_team_UNIQUE` (`id_mechanic_team` ASC),
  INDEX `fk_mechanic_team_mechanic1_idx` (`mechanic_person_id_person` ASC),
  CONSTRAINT `fk_mechanic_team_mechanic1`
    FOREIGN KEY (`mechanic_person_id_person`)
    REFERENCES `mechanicalworkshop`.`mechanic` (`person_id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`part` (
  `id_part` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(155) NOT NULL,
  `description` TEXT NOT NULL,
  `manufacturer` VARCHAR(155) NOT NULL,
  `quantity` INT NOT NULL,
  `cost` FLOAT NOT NULL,
  `manufacture_year` INT NOT NULL,
  PRIMARY KEY (`id_part`),
  UNIQUE INDEX `idpart_UNIQUE` (`id_part` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`vehicle` (
  `id_vehicle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(155) NOT NULL,
  `color` VARCHAR(155) NOT NULL,
  `license_plate` VARCHAR(8) NOT NULL,
  `model` VARCHAR(155) NOT NULL,
  `mileage` FLOAT NOT NULL,
  `client_id_client` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_vehicle`),
  UNIQUE INDEX `idvehicle_UNIQUE` (`id_vehicle` ASC) VISIBLE,
  UNIQUE INDEX `license_plate_UNIQUE` (`license_plate` ASC) VISIBLE,
  INDEX `fk_vehicle_client1_idx` (`client_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `mechanicalworkshop`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`service_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`service_order` (
  `id_service_order` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `part_id_part` INT(10) UNSIGNED NOT NULL,
  `entry_date` DATETIME NOT NULL,
  `exit_date` DATETIME NOT NULL,
  `defect_description` TEXT NOT NULL,
  `vehicle_id_vehicle_fk` INT(10) UNSIGNED NOT NULL,
  `client_id_client_fk` INT(10) UNSIGNED NOT NULL,
  `admin_person_id_person_fk` INT(10) UNSIGNED NOT NULL,
  `mechanic_team_id_mechanic_team` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_service_order`),
  UNIQUE INDEX `id_service_order_UNIQUE` (`id_service_order` ASC),
  INDEX `fk_service_order_vehicle1_idx` (`vehicle_id_vehicle_fk` ASC),
  INDEX `fk_service_order_client1_idx` (`client_id_client_fk` ASC),
  INDEX `fk_service_order_admin1_idx` (`admin_person_id_person_fk` ASC),
  INDEX `fk_service_order_mechanic_team1_idx` (`mechanic_team_id_mechanic_team` ASC),
  CONSTRAINT `fk_service_order_admin1`
    FOREIGN KEY (`admin_person_id_person_fk`)
    REFERENCES `mechanicalworkshop`.`admin` (`person_id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_order_client1`
    FOREIGN KEY (`client_id_client_fk`)
    REFERENCES `mechanicalworkshop`.`client` (`id_client`),
  CONSTRAINT `fk_service_order_vehicle1`
    FOREIGN KEY (`vehicle_id_vehicle_fk`)
    REFERENCES `mechanicalworkshop`.`vehicle` (`id_vehicle`),
  CONSTRAINT `fk_service_order_mechanic_team1`
    FOREIGN KEY (`mechanic_team_id_mechanic_team`)
    REFERENCES `mechanicalworkshop`.`mechanic_team` (`id_mechanic_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`part_service_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`part_service_order` (
  `part_id_part` INT(10) UNSIGNED NOT NULL,
  `service_order_id_service_order` INT(10) UNSIGNED NOT NULL,
  UNIQUE INDEX `part_id_part_UNIQUE` (`part_id_part` ASC),
  UNIQUE INDEX `service_order_id_service_order_UNIQUE` (`service_order_id_service_order` ASC),
  INDEX `fk_part_has_service_order_service_order1_idx` (`service_order_id_service_order` ASC),
  INDEX `fk_part_has_service_order_part1_idx` (`part_id_part` ASC),
  CONSTRAINT `fk_part_has_service_order_part1`
    FOREIGN KEY (`part_id_part`)
    REFERENCES `mechanicalworkshop`.`part` (`id_part`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_part_has_service_order_service_order1`
    FOREIGN KEY (`service_order_id_service_order`)
    REFERENCES `mechanicalworkshop`.`service_order` (`id_service_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`vehicle_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`vehicle_client` (
  `client_id_client_fk` INT(10) UNSIGNED NOT NULL,
  `vehicle_id_vehicle_fk` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_client_has_vehicle_vehicle1_idx` (`vehicle_id_vehicle_fk` ASC),
  INDEX `fk_client_has_vehicle_client1_idx` (`client_id_client_fk` ASC),
  CONSTRAINT `fk_client_has_vehicle_client1`
    FOREIGN KEY (`client_id_client_fk`)
    REFERENCES `mechanicalworkshop`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_vehicle_vehicle1`
    FOREIGN KEY (`vehicle_id_vehicle_fk`)
    REFERENCES `mechanicalworkshop`.`vehicle` (`id_vehicle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mechanicalworkshop`.`verification_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mechanicalworkshop`.`verification_code` (
  `code` INT(11) NOT NULL,
  `code_used` TINYINT(4) NOT NULL,
  `code_time` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `person_id_person` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_verification_code_person1_idx` (`person_id_person` ASC),
  CONSTRAINT `fk_verification_code_person1`
    FOREIGN KEY (`person_id_person`)
    REFERENCES `mechanicalworkshop`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
